#!/bin/sh
#
# Run csi-sanity (https://github.com/kubernetes-csi/csi-test) against the
# ZeroFS CSI driver running in a kind cluster.
#
# The driver needs a Kubernetes API to provision volumes, so it runs inside a
# kind cluster.  csi-sanity itself runs on the host and talks to the
# zerofs-csi-sanity pod (see test/sanity/plugin.yaml) over TCP.  Staging and
# target paths live inside that pod, so csi-sanity's path management hooks are
# small kubectl exec shims generated by this script - the same approach the
# upstream csi prow jobs use.
#
# Usage:
#   make sanity-test
#
# Environment:
#   KIND_CLUSTER       kind cluster name (default: zerofs-sanity)
#   CSI_SANITY_BIN     csi-sanity binary (default: $(go env GOPATH)/bin/csi-sanity)
#   CSI_SANITY_ARGS    extra arguments passed to csi-sanity
#   CSI_SANITY_SKIP    replaces the default --ginkgo.skip pattern
#   KEEP_CLUSTER       set to 1 to keep the kind cluster on exit

set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)
KIND_CLUSTER="${KIND_CLUSTER:-zerofs-sanity}"
KUBE_CONTEXT="kind-${KIND_CLUSTER}"
KEEP_CLUSTER="${KEEP_CLUSTER:-0}"
NAMESPACE="zerofs-csi"
SANITY_POD="zerofs-csi-sanity"
SANITY_CONTAINER="zerofs-plugin"
SANITY_PORT=10000
DRIVER_IMAGE="${DRIVER_IMAGE:-ghcr.io/sorend/csi-driver-zerofs:latest}"
ZEROFS_IMAGE="${ZEROFS_IMAGE:-ghcr.io/barre/zerofs:1.0.4}"
BUCKET="${BUCKET:-zerofs-data}"
WORK_DIR="${WORK_DIR:-/tmp/csi-sanity}"

CSI_SANITY_BIN="${CSI_SANITY_BIN:-$(go env GOPATH)/bin/csi-sanity}"
CSI_SANITY_ARGS="${CSI_SANITY_ARGS:-}"

# csi-sanity calls NodeExpandVolume without a capacity range and expects
# NOT_FOUND because the volume does not exist.  The CSI specification asks for
# INVALID_ARGUMENT when the capacity range is missing, and the node service is
# stateless so it cannot know whether a volume exists.
CSI_SANITY_SKIP="${CSI_SANITY_SKIP:-NodeExpandVolume should fail when volume is not found}"

log() {
    echo "==> $*"
}

kubectl_cmd() {
    kubectl --context "$KUBE_CONTEXT" "$@"
}

# generate_path_hooks writes the create/remove/check path commands handed to
# csi-sanity.  Every hook receives the path as $1; "create" prints the path on
# stdout, "check" prints file|directory|not_found|other.
generate_path_hooks() {
    mkdir -p "${WORK_DIR}/hooks"

    cat >"${WORK_DIR}/hooks/create-path.sh" <<EOF
#!/bin/sh
set -eu
kubectl --context ${KUBE_CONTEXT} exec -n ${NAMESPACE} ${SANITY_POD} -c ${SANITY_CONTAINER} -- mkdir -p "\$1"
echo "\$1"
EOF

    cat >"${WORK_DIR}/hooks/remove-path.sh" <<EOF
#!/bin/sh
set -eu
kubectl --context ${KUBE_CONTEXT} exec -n ${NAMESPACE} ${SANITY_POD} -c ${SANITY_CONTAINER} -- rm -rf "\$1"
EOF

    cat >"${WORK_DIR}/hooks/check-path.sh" <<EOF
#!/bin/sh
set -eu
kubectl --context ${KUBE_CONTEXT} exec -n ${NAMESPACE} ${SANITY_POD} -c ${SANITY_CONTAINER} \\
    -- /bin/sh -c 'if [ -f "\$1" ]; then echo file; elif [ -d "\$1" ]; then echo directory; elif [ -e "\$1" ]; then echo other; else echo not_found; fi' sh "\$1"
EOF

    chmod +x "${WORK_DIR}/hooks/create-path.sh" \
        "${WORK_DIR}/hooks/remove-path.sh" \
        "${WORK_DIR}/hooks/check-path.sh"
}

teardown() {
    if [ "$KEEP_CLUSTER" = "1" ]; then
        log "Keeping kind cluster ${KIND_CLUSTER} (context ${KUBE_CONTEXT})"
    else
        log "Deleting kind cluster ${KIND_CLUSTER}"
        kind delete cluster --name "$KIND_CLUSTER" >/dev/null 2>&1 || true
    fi
}

dump_debug() {
    log "csi-sanity plugin logs"
    kubectl_cmd logs -n "$NAMESPACE" "$SANITY_POD" -c "$SANITY_CONTAINER" --tail=100 || true
    log "CSI controller logs"
    kubectl_cmd logs -n "$NAMESPACE" deployment/zerofs-csi-controller -c zerofs-plugin --tail=50 || true
    log "Pods in ${NAMESPACE}"
    kubectl_cmd get pods -n "$NAMESPACE" -o wide || true
    log "ZeroFS deployments in ${NAMESPACE}"
    kubectl_cmd get deployments -n "$NAMESPACE" || true
}

if [ ! -x "$CSI_SANITY_BIN" ]; then
    echo "csi-sanity not found at ${CSI_SANITY_BIN}; run 'make csi-sanity-install' first" >&2
    exit 1
fi

trap teardown EXIT

kind delete cluster --name "$KIND_CLUSTER" >/dev/null 2>&1 || true

log "Creating kind cluster ${KIND_CLUSTER}"
kind create cluster --name "$KIND_CLUSTER" --config "${ROOT_DIR}/test/kind-config.yaml" --wait 120s

log "Building driver image ${DRIVER_IMAGE}"
docker build -t "$DRIVER_IMAGE" "$ROOT_DIR"

log "Loading driver image into kind"
kind load docker-image "$DRIVER_IMAGE" --name "$KIND_CLUSTER"

log "Pulling ZeroFS server image ${ZEROFS_IMAGE} into kind"
docker exec "${KIND_CLUSTER}-control-plane" \
    ctr --namespace=k8s.io images pull "$ZEROFS_IMAGE"

log "Deploying CSI driver"
kubectl_cmd apply -f "${ROOT_DIR}/deploy/install.yaml"
kubectl_cmd patch deployment zerofs-csi-controller -n "$NAMESPACE" \
    --type=strategic \
    -p '{"spec":{"template":{"spec":{"containers":[{"name":"zerofs-plugin","imagePullPolicy":"Never"}]}}}}'
kubectl_cmd patch daemonset zerofs-csi-node -n "$NAMESPACE" \
    --type=strategic \
    -p '{"spec":{"template":{"spec":{"containers":[{"name":"zerofs-plugin","imagePullPolicy":"Never"}]}}}}'
kubectl_cmd rollout status deployment/zerofs-csi-controller -n "$NAMESPACE" --timeout=180s
kubectl_cmd rollout status daemonset/zerofs-csi-node -n "$NAMESPACE" --timeout=180s

log "Deploying RustFS"
kubectl_cmd apply -f "${ROOT_DIR}/test/rustfs.yaml"
kubectl_cmd rollout status deployment/rustfs -n "$NAMESPACE" --timeout=180s

log "Creating bucket ${BUCKET}"
kubectl_cmd delete pod s3-init -n "$NAMESPACE" --ignore-not-found >/dev/null 2>&1 || true
kubectl_cmd run s3-init \
    --image=amazon/aws-cli:latest \
    --restart=Never \
    -n "$NAMESPACE" \
    --env=AWS_ACCESS_KEY_ID=minioadmin \
    --env=AWS_SECRET_ACCESS_KEY=minioadmin123 \
    --env=AWS_DEFAULT_REGION=us-east-1 \
    --command -- /bin/sh -c \
    "aws --endpoint-url http://rustfs.${NAMESPACE}.svc.cluster.local:9000 s3api head-bucket --bucket ${BUCKET} >/dev/null 2>&1 || aws --endpoint-url http://rustfs.${NAMESPACE}.svc.cluster.local:9000 s3 mb s3://${BUCKET}"
kubectl_cmd wait pod/s3-init -n "$NAMESPACE" \
    --for=jsonpath='{.status.phase}'=Succeeded --timeout=180s

log "Deploying csi-sanity plugin"
kubectl_cmd apply -f "${ROOT_DIR}/test/sanity/plugin.yaml"
kubectl_cmd wait pod/"$SANITY_POD" -n "$NAMESPACE" --for=condition=Ready --timeout=180s

generate_path_hooks

NODE_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "${KIND_CLUSTER}-control-plane")
ENDPOINT="dns:///${NODE_IP}:${SANITY_PORT}"
log "csi-sanity endpoint: ${ENDPOINT}"

rm -rf "${WORK_DIR}/mount" "${WORK_DIR}/staging"

log "Running csi-sanity"
set +e
# shellcheck disable=SC2086
"$CSI_SANITY_BIN" \
    --ginkgo.v \
    --ginkgo.no-color \
    --ginkgo.junit-report "${WORK_DIR}/junit_sanity.xml" \
    --ginkgo.skip "$CSI_SANITY_SKIP" \
    --csi.endpoint "$ENDPOINT" \
    --csi.mountdir "${WORK_DIR}/mount" \
    --csi.stagingdir "${WORK_DIR}/staging" \
    --csi.createmountpathcmd "${WORK_DIR}/hooks/create-path.sh" \
    --csi.createstagingpathcmd "${WORK_DIR}/hooks/create-path.sh" \
    --csi.removemountpathcmd "${WORK_DIR}/hooks/remove-path.sh" \
    --csi.removestagingpathcmd "${WORK_DIR}/hooks/remove-path.sh" \
    --csi.checkpathcmd "${WORK_DIR}/hooks/check-path.sh" \
    --csi.testvolumeparameters "${ROOT_DIR}/test/sanity/params.yaml" \
    $CSI_SANITY_ARGS
RESULT=$?
set -e

if [ "$RESULT" -ne 0 ]; then
    dump_debug
fi

exit "$RESULT"
